### ISSUE TITLE
Namespace: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by meabed** [i18next/next-i18next#1913]
## 🐛 Bug Report

Error with namespace .forEach

```
error - TypeError: Cannot read properties of undefined (reading 'forEach')
    at /node_modules/i18next/dist/cjs/i18next.js:1912:20
    at Array.forEach (<anonymous>)
    at Connector.queueLoad (/node_modules/i18next/dist/cjs/i18next.js:1910:17)
    at Connector.prepareLoading (/node_modules/i18next/dist/cjs/i18next.js:2048:25)
    at Connector.load (/node_modules/i18next/dist/cjs/i18next.js:2062:12)
    at I18n.loadResources (/node_modules/i18next/dist/cjs/i18next.js:2459:40)
    at setLng (/node_modules/i18next/dist/cjs/i18next.js:2585:16)
    at I18n.changeLanguage (/node_modules/i18next/dist/cjs/i18next.js:2595:9)
    at load (/node_modules/i18next/dist/cjs/i18next.js:2409:16)
    at I18n.init (/node_modules/i18next/dist/cjs/i18next.js:2413:9) {
  page: '/'
```

## To Reproduce

A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
const HttpBackend = require('i18next-http-backend/cjs');
const ChainedBackend = require('i18next-chained-backend').default;
const LocalStorageBackend = require('i18next-localstorage-backend').default;

const isProd = process.env.NODE_ENV === 'production';

module.exports = {
  backend: {
    backendOptions: [{ expirationTime: !isProd ? 0 : 30 * 60 * 1000 }, {}], // Translation cached for 30 min on production
    backends: typeof window !== 'undefined' ? [LocalStorageBackend, HttpBackend] : []
  },
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'es']
  },
  serializeConfig: false,
  use: typeof window !== 'undefined' ? [ChainedBackend] : [],
  reloadOnPrerender: !isProd
};
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment
- nextjs: 12.2.2
- next-i18next: 11.2.1
- node: 18

**Comment by adrai** [comment]
can you try with v11.2.2 ?

**Comment by meabed** [comment]
Yes, its fixed and works fine 👍

**Comment by adrai** [comment]
//cc: @felixmosh
