### ISSUE TITLE
Build failing on Amplify with NextJS

### ISSUE THREAD

**Issue by ItzaMi** [i18next/next-i18next#1932]
## 🐛 Bug Report

Currently deploying a project with Amplify and build is failing. I have another project with an identical setup and there were no issues there.

Current log on Amplify
```
2022-08-22T13:59:11.258Z [INFO]: Starting SSR Build...
2022-08-22T14:01:35.464Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  warn  - Invalid next.config.js options detected:
                                  [
                                  {
                                  "instancePath": "",
                                  "schemaPath": "#/additionalProperties",
                                  "keyword": "additionalProperties",
                                  "params": {
                                  "additionalProperty": "target"
                                  },
                                  "message": "must NOT have additional properties"
                                  }
                                  ]
                                  See more info here: https://nextjs.org/docs/messages/invalid-next-config
                                  warn  - The `target` config is deprecated and will be removed in a future version.
                                  See more info here https://nextjs.org/docs/messages/deprecated-target-config
                                  warn  - Compiled with warnings
                                  ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
                                  Critical dependency: the request of a dependency is an expression
                                  Import trace for requested module:
                                  ./node_modules/next-i18next/serverSideTranslations.js
                                  ./pages/sign-in.tsx
                                  ./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?absolute404Path=&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolutePagePath=private-next-pages%2Fsign-in.tsx&assetPrefix=&basePath=&buildId=S643Z1AY2W7HVZueTRsLW&canonicalBase=&distDir=private-dot-next&generateEtags=true&i18n=%7B%22defaultLocale%22%3A%22en%22%2C%22locales%22%3A%5B%22en%22%5D%7D&loadedEnvFiles=W10%3D&page=%2Fsign-in&poweredByHeader=true&previewProps=%7B%22previewModeId%22%3A%225387d84d5a3a2cdcb710f154601f6fa2%22%2C%22previewModeSigningKey%22%3A%223811142fcf8c5c1f41d051f3bff86bbfe7407fddb1c6c456629ad06a65e2a132%22%2C%22previewModeEncryptionKey%22%3A%2225de7bdd5447403fe29a7a49d26fdc6c06c4caac8338a2518efa9c528c9cd842%22%7D&runtimeConfig=!
                                  ./node_modules/i18next-fs-backend/cjs/readFile.js
                                  Critical dependency: the request of a dependency is an expression
                                  Import trace for requested module:
                                  ./node_modules/i18next-fs-backend/cjs/index.js
                                  ./node_modules/next-i18next/dist/commonjs/createClient/node.js
                                  ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
                                  ./node_modules/next-i18next/serverSideTranslations.js
                                  ./pages/sign-in.tsx
                                  ./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?absolute404Path=&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolutePagePath=private-next-pages%2Fsign-in.tsx&assetPrefix=&basePath=&buildId=S643Z1AY2W7HVZueTRsLW&canonicalBase=&distDir=private-dot-next&generateEtags=true&i18n=%7B%22defaultLocale%22%3A%22en%22%2C%22locales%22%3A%5B%22en%22%5D%7D&loadedEnvFiles=W10%3D&page=%2Fsign-in&poweredByHeader=true&previewProps=%7B%22previewModeId%22%3A%225387d84d5a3a2cdcb710f154601f6fa2%22%2C%22previewModeSigningKey%22%3A%223811142fcf8c5c1f41d051f3bff86bbfe7407fddb1c6c456629ad06a65e2a132%22%2C%22previewModeEncryptionKey%22%3A%2225de7bdd5447403fe29a7a49d26fdc6c06c4caac8338a2518efa9c528c9cd842%22%7D&runtimeConfig=!
                                  ./node_modules/i18next-fs-backend/cjs/readFile.js
                                  Critical dependency: the request of a dependency is an expression
                                  Import trace for requested module:
                                  ./node_modules/i18next-fs-backend/cjs/index.js
                                  ./node_modules/next-i18next/dist/commonjs/createClient/node.js
                                  ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
                                  ./node_modules/next-i18next/serverSideTranslations.js
                                  ./pages/sign-in.tsx
                                  ./node_modules/next/dist/build/webpack/loaders/next--loader/index.js?absolute404Path=&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolutePagePath=private-next-pages%2Fsign-in.tsx&assetPrefix=&basePath=&buildId=S643Z1AY2W7HVZueTRsLW&canonicalBase=&distDir=private-dot-next&generateEtags=true&i18n=%7B%22defaultLocale%22%3A%22en%22%2C%22locales%22%3A%5B%22en%22%5D%7D&loadedEnvFiles=W10%3D&page=%2Fsign-in&poweredByHeader=true&previewProps=%7B%22previewModeId%22%3A%225387d84d5a3a2cdcb710f154601f6fa2%22%2C%22previewModeSigningKey%22%3A%223811142fcf8c5c1f41d051f3bff86bbfe7407fddb1c6c456629ad06a65e2a132%22%2C%22previewModeEncryptionKey%22%3A%2225de7bdd5447403fe29a7a49d26fdc6c06c4caac8338a2518efa9c528c9cd842%22%7D&runtimeConfig=!
                                  Unhandled error during request: Error: Cannot find module '/codebuild/output/src175349801/src/dashboard/next-i18next.config.js'
                                  at webpackEmptyContext (/codebuild/output/src175349801/src/dashboard/.next//pages/sign-in.js:11:10)
                                  at /codebuild/output/src175349801/src/dashboard/.next//chunks/190.js:6029:72 {
                                  code: 'MODULE_NOT_FOUND'
                                  }
                                  Error occurred prerendering page "/en/sign-in". Read more: https://nextjs.org/docs/messages/prerender-error
                                  Error: Cannot find module '/codebuild/output/src175349801/src/dashboard/next-i18next.config.js'
                                  at webpackEmptyContext (/codebuild/output/src175349801/src/dashboard/.next//pages/sign-in.js:11:10)
                                  at /codebuild/output/src175349801/src/dashboard/.next//chunks/190.js:6029:72
                                  > Build error occurred
                                  Error: Export encountered errors on following paths:
                                  /sign-in: /en/sign-in
                                  at /codebuild/output/src175349801/src/dashboard/node_modules/next/dist/export/index.js:395:19
                                  at runMicrotasks (<anonymous>)
                                  at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                  at async Span.traceAsyncFn (/codebuild/output/src175349801/src/dashboard/node_modules/next/dist/trace/trace.js:79:20)
                                  at async /codebuild/output/src175349801/src/dashboard/node_modules/next/dist/build/index.js:1094:21
                                  at async Span.traceAsyncFn (/codebuild/output/src175349801/src/dashboard/node_modules/next/dist/trace/trace.js:79:20)
                                  at async /codebuild/output/src175349801/src/dashboard/node_modules/next/dist/build/index.js:971:17
                                  at async Span.traceAsyncFn (/codebuild/output/src175349801/src/dashboard/node_modules/next/dist/trace/trace.js:79:20)
                                  at async Object.build [as default] (/codebuild/output/src175349801/src/dashboard/node_modules/next/dist/build/index.js:64:29)
                                  info  - Linting and checking validity of types...
                                  info  - Creating an optimized production build...
                                  info  - Collecting page data...
                                  info  - Generating static pages (0/7)
                                  info  - Generating static pages (1/7)
                                  info  - Generating static pages (3/7)
                                  info  - Generating static pages (5/7)
                                  info  - Generating static pages (7/7)
                                  at makeError (/root/.//node_modules/execa/lib/error.js:60:11)
                                  at handlePromise (/root/.//node_modules/execa/index.js:118:26)
                                  at runMicrotasks (<anonymous>)
                                  at processTicksAndRejections (internal/process/task_queues.js:95:5)
                                  at async Builder.build (/root/.//node_modules/@sls-next/lambda-at-edge/dist/build.js:377:13)
                                  at async NextjsComponent.build (/root/.//node_modules/@sls-next/-component/dist/component.js:165:13)
                                  at async NextjsComponent.default (/root/.//node_modules/@sls-next/-component/dist/component.js:22:13)
                                  at async fn (/root/.npm/_npx/1232/lib/node_modules//node_modules/@/template/utils.js:280:41)
                                  at async Promise.all (index 0)
                                  at async executeGraph (/root/.npm/_npx/1232/lib/node_modules//node_modules/@/template/utils.js:294:3)
                                  at async Template.default (/root/.npm/_npx/1232/lib/node_modules//node_modules/@/template/.js:67:38)
                                  at async Object.runComponents (/root/.npm/_npx/1232/lib/node_modules//node_modules/@/cli/src/index.js:222:17) {
                                  shortMessage: 'Command failed with exit code 1: node_modules/.bin/next build',
                                  command: 'node_modules/.bin/next build',
                                  escapedCommand: '"node_modules/.bin/next" build',
                                  exitCode: 1,
                                  signal: undefined,
                                  signalDescription: undefined,
                                  stdout: 'info  - Linting and checking validity of types...\n' +
                                  'info  - Creating an optimized production build...\n' +
                                  'info  - Collecting page data...\n' +
                                  'info  - Generating static pages (0/7)\n' +
                                  'info  - Generating static pages (1/7)\n' +
                                  'info  - Generating static pages (3/7)\n' +
                                  'info  - Generating static pages (5/7)\n' +
                                  'info  - Generating static pages (7/7)',
                                  stderr: 'warn  - Invalid next.config.js options detected: \n' +
                                  '[\n' +
                                  '  {\n' +
                                  '    "instancePath": "",\n' +
                                  '    "schemaPath": "#/additionalProperties",\n' +
                                  '    "keyword": "additionalProperties",\n' +
                                  '    "params": {\n' +
                                  '      "additionalProperty": "target"\n' +
                                  '    },\n' +
                                  '    "message": "must NOT have additional properties"\n' +
                                  '  }\n' +
                                  '] \n' +
                                  'See more info here: https://nextjs.org/docs/messages/invalid-next-config\n' +
                                  'warn  - The `target` config is deprecated and will be removed in a future version.\n' +
                                  'See more info here https://nextjs.org/docs/messages/deprecated-target-config\n' +
                                  'warn  - Compiled with warnings\n' +
                                  '\n' +
                                  './node_modules/next-i18next/dist/commonjs/serverSideTranslations.js\n' +
                                  'Critical dependency: the request of a dependency is an expression\n' +
                                  '\n' +
                                  'Import trace for requested module:\n' +
                                  './node_modules/next-i18next/serverSideTranslations.js\n' +
                                  './pages/sign-in.tsx\n' +
                                  './node_modules/next/dist/build/webpack/loaders/next--loader/index.js?absolute404Path=&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolutePagePath=private-next-pages%2Fsign-in.tsx&assetPrefix=&basePath=&buildId=S643Z1AY2W7HVZueTRsLW&canonicalBase=&distDir=private-dot-next&generateEtags=true&i18n=%7B%22defaultLocale%22%3A%22en%22%2C%22locales%22%3A%5B%22en%22%5D%7D&loadedEnvFiles=W10%3D&page=%2Fsign-in&poweredByHeader=true&previewProps=%7B%22previewModeId%22%3A%225387d84d5a3a2cdcb710f154601f6fa2%22%2C%22previewModeSigningKey%22%3A%223811142fcf8c5c1f41d051f3bff86bbfe7407fddb1c6c456629ad06a65e2a132%22%2C%22previewModeEncryptionKey%22%3A%2225de7bdd5447403fe29a7a49d26fdc6c06c4caac8338a2518efa9c528c9cd842%22%7D&runtimeConfig=!\n' +
                                  '\n' +
                                  './node_modules/i18next-fs-backend/cjs/readFile.js\n' +
                                  'Critical dependency: the request of a dependency is an expression\n' +
                                  '\n' +
                                  'Import trace for requested module:\n' +
                                  './node_modules/i18next-fs-backend/cjs/index.js\n' +
                                  './node_modules/next-i18next/dist/commonjs/createClient/node.js\n' +
                                  './node_modules/next-i18next/dist/commonjs/serverSideTranslations.js\n' +
                                  './node_modules/next-i18next/serverSideTranslations.js\n' +
                                  './pages/sign-in.tsx\n' +
                                  './node_modules/next/dist/build/webpack/loaders/next--loader/index.js?absolute404Path=&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolutePagePath=private-next-pages%2Fsign-in.tsx&assetPrefix=&basePath=&buildId=S643Z1AY2W7HVZueTRsLW&canonicalBase=&distDir=private-dot-next&generateEtags=true&i18n=%7B%22defaultLocale%22%3A%22en%22%2C%22locales%22%3A%5B%22en%22%5D%7D&loadedEnvFiles=W10%3D&page=%2Fsign-in&poweredByHeader=true&previewProps=%7B%22previewModeId%22%3A%225387d84d5a3a2cdcb710f154601f6fa2%22%2C%22previewModeSigningKey%22%3A%223811142fcf8c5c1f41d051f3bff86bbfe7407fddb1c6c456629ad06a65e2a132%22%2C%22previewModeEncryptionKey%22%3A%2225de7bdd5447403fe29a7a49d26fdc6c06c4caac8338a2518efa9c528c9cd842%22%7D&runtimeConfig=!\n' +
                                  '\n' +
                                  './node_modules/i18next-fs-backend/cjs/readFile.js\n' +
                                  'Critical dependency: the request of a dependency is an expression\n' +
                                  '\n' +
                                  'Import trace for requested module:\n' +
                                  './node_modules/i18next-fs-backend/cjs/index.js\n' +
                                  './node_modules/next-i18next/dist/commonjs/createClient/node.js\n' +
                                  './node_modules/next-i18next/dist/commonjs/serverSideTranslations.js\n' +
                                  './node_modules/next-i18next/serverSideTranslations.js\n' +
                                  './pages/sign-in.tsx\n' +
                                  './node_modules/next/dist/build/webpack/loaders/next--loader/index.js?absolute404Path=&absoluteAppPath=private-next-pages%2F_app.tsx&absoluteDocumentPath=private-next-pages%2F_document.tsx&absoluteErrorPath=next%2Fdist%2Fpages%2F_error&absolutePagePath=private-next-pages%2Fsign-in.tsx&assetPrefix=&basePath=&buildId=S643Z1AY2W7HVZueTRsLW&canonicalBase=&distDir=private-dot-next&generateEtags=true&i18n=%7B%22defaultLocale%22%3A%22en%22%2C%22locales%22%3A%5B%22en%22%5D%7D&loadedEnvFiles=W10%3D&page=%2Fsign-in&poweredByHeader=true&previewProps=%7B%22previewModeId%22%3A%225387d84d5a3a2cdcb710f154601f6fa2%22%2C%22previewModeSigningKey%22%3A%223811142fcf8c5c1f41d051f3bff86bbfe7407fddb1c6c456629ad06a65e2a132%22%2C%22previewModeEncryptionKey%22%3A%2225de7bdd5447403fe29a7a49d26fdc6c06c4caac8338a2518efa9c528c9cd842%22%7D&runtimeConfig=!\n' +
                                  '\n' +
                                  "Unhandled error during request: Error: Cannot find module '/codebuild/output/src175349801/src/dashboard/next-i18next.config.js'\n" +
                                  '    at webpackEmptyContext (/codebuild/output/src175349801/src/dashboard/.next//pages/sign-in.js:11:10)\n' +
                                  '    at /codebuild/output/src175349801/src/dashboard/.next//chunks/190.js:6029:72 {\n' +
                                  "  code: 'MODULE_NOT_FOUND'\n" +
                                  '}\n' +
                                  '\n' +
                                  'Error occurred prerendering page "/en/sign-in". Read more: https://nextjs.org/docs/messages/prerender-error\n' +
                                  "Error: Cannot find module '/codebuild/output/src175349801/src/dashboard/next-i18next.config.js'\n" +
                                  '    at webpackEmptyContext (/codebuild/output/src175349801/src/dashboard/.next//pages/sign-in.js:11:10)\n' +
                                  '    at /codebuild/output/src175349801/src/dashboard/.next//chunks/190.js:6029:72\n' +
                                  '\n' +
                                  '> Build error occurred\n' +
                                  'Error: Export encountered errors on following paths:\n' +
                                  '\t/sign-in: /en/sign-in\n' +
                                  '    at /codebuild/output/src175349801/src/dashboard/node_modules/next/dist/export/index.js:395:19\n' +
                                  '    at runMicrotasks (<anonymous>)\n' +
                                  '    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/src175349801/src/dashboard/node_modules/next/dist/trace/trace.js:79:20)\n' +
                                  '    at async /codebuild/output/src175349801/src/dashboard/node_modules/next/dist/build/index.js:1094:21\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/src175349801/src/dashboard/node_modules/next/dist/trace/trace.js:79:20)\n' +
                                  '    at async /codebuild/output/src175349801/src/dashboard/node_modules/next/dist/build/index.js:971:17\n' +
                                  '    at async Span.traceAsyncFn (/codebuild/output/src175349801/src/dashboard/node_modules/next/dist/trace/trace.js:79:20)\n' +
                                  '    at async Object.build [as default] (/codebuild/output/src175349801/src/dashboard/node_modules/next/dist/build/index.js:64:29)',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
                                  killed: false
                                  }
```

## To Reproduce

```js
// next-i18next.config.js
module.exports = {
  defaultNS: 'sign-in',
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
  interpolation: {
    escapeValue: false,
  },
  returnObjects: true,
}
```

```js
// next.config.js
const { i18n } = require('./next-i18next.config.js')

/** @type {import('next').NextConfig} */
const nextConfig = {
  i18n,
}

module.exports = nextConfig
```

```js
// _app.tsx
import { useEffect } from 'react'
import type { AppProps } from 'next/app'
import Router from 'next/router'
import { appWithTranslation } from 'next-i18next'

import '../styles/shared/reset.css'
import 'react-phone-input-2/lib/style.css'
import '../styles/components/PhoneNumberInput/phone-number-input.css'
import '../styles/globals.css'

function MyApp({ Component, pageProps }: AppProps) {
  /**
   * This function breaks while using `useRouter`
   * A similar issue (and its solution) can be seen here 👇
   * https://github.com/vercel/next.js/issues/18127#issuecomment-950907739
   */
  useEffect(() => {
    const prevToken = window.localStorage.getItem('MY_USER_TOKEN')

    if (!prevToken) {
      Router.push('/sign-in')
    } else {
      Router.push('/')
    }
  }, [])

  return <Component {...pageProps} />
}

export default appWithTranslation(MyApp)
```

## Expected behavior

Build locally works fine so was expecting for the same to happen on Amplify

## Your Environment

- *runtime version*: node v14
- *i18next version*: "next-i18next": "^11.3.0",
- *os*: Mac

**Comment by ItzaMi** [comment]
> This may help: #1928

I've read that. As you can see, I'm already declaring the rest of the properties outside

**Comment by adrai** [comment]
Based on your log it seems there is some property with the name "target"... there's not much I can help without a reproducible example.

**Comment by ItzaMi** [comment]
@adrai, notice that that is just a `warn` and not an `error`.
Also, `target` is coming from
```
                                  warn  - Invalid next.config.js options detected:
                                  [
                                  {
                                  "instancePath": "",
                                  "schemaPath": "#/additionalProperties",
                                  "keyword": "additionalProperties",
                                  "params": {
                                  "additionalProperty": "target"
                                  },
                                  "message": "must NOT have additional properties"
                                  }
                                  ]
                                  See more info here: https://nextjs.org/docs/messages/invalid-next-config
                                  warn  - The `target` config is deprecated and will be removed in a future version.
```
As you can see, there's no reference to any `target` within my `next.config.js`, nor anywhere in the code.

I would say that the important parts are
```
Error occurred prerendering page "/en/sign-in". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Cannot find module '/codebuild/output/src175349801/src/dashboard/next-i18next.config.js'
```

**Comment by adrai** [comment]
Provide a minimal reproducible example please. Just create a github repo and share the link.

**Comment by ItzaMi** [comment]
Here it is: https://github.com/ItzaMi/next-i18next-amplify-build-bug

**Comment by adrai** [comment]
you missed to add the en folder here:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/1086194/186005593-4d4fa2aa-acc6-495a-ba5a-72eeabfe7ec7.png">

then it works...
`npm run dev`:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/1086194/186005660-741f8938-3d9c-44ee-a548-a0c5b36739c8.png">

`npm run build`:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/1086194/186005727-6ccd1994-f0dc-45fc-8a61-eca35c839e42.png">


<img width="356" alt="image" src="https://user-images.githubusercontent.com/1086194/186005768-b18e7229-3779-4b62-bc1b-aa8b6b0f6999.png">

**Comment by ItzaMi** [comment]
Correct, i missed the ‘en’ on the reproduction. However, the local build was never the issue.
Like i mentioned in the initial issue, thats the log that I get from Amplify and the build issue is there.
Without the ‘next-i18n’ dependency and setup the build runs perfectly

**Comment by adrai** [comment]
you might then ask amplify... or stackoverflow

**Comment by adrai** [comment]
adding this link just for information: https://github.com/aws-amplify/amplify-hosting/issues/2111

this might also be related: https://github.com/i18next/next-i18next/issues/1434

**Comment by ItzaMi** [comment]
So, was able to solve this on Amplify by adding a new variable: ` AMPLIFY_NEXTJS_EXPERIMENTAL_TRACE=true`
https://github.com/aws-amplify/amplify-hosting/issues/2427

**Comment by multivoltage** [comment]
did you solve in other way since I hate that flag?
