### ISSUE TITLE
next build and pages with getStaticProps throw an error

### ISSUE THREAD

**Issue by sajadghawami** [i18next/next-i18next#1986]
Hey there,

## 🐛 Bug Report

unfortunately, after upgrading nextjs and i18next i am currently getting a weird error but *only* concerning pages that use `getStaticProps`.  So pages that use `getServerSideProps` are unaffected by this error:

## Error:

```
Error occurred prerendering page "/de/sign-up". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'useMemo')
    at exports.useMemo (/XXX/node_modules/react-i18next/node_modules/react/cjs/react.production.min.js:25:208)
    at I18nextProvider (/XXX/node_modules/react-i18next/dist/commonjs/I18nextProvider.js:16:34)
    at Wc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
TypeError: Cannot read properties of null (reading 'useMemo')
    at exports.useMemo (/XXX/node_modules/react-i18next/node_modules/react/cjs/react.production.min.js:25:208)
    at I18nextProvider (/XXX/node_modules/react-i18next/dist/commonjs/I18nextProvider.js:16:34)
    at Wc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
    at Z (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/XXX/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
```

## To Reproduce

```js
const Activate: React.FunctionComponent<any> = () => {... };
export default Activate;

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
}

```

`next-i18next.config`

```
const path = require('path');

module.exports = {
  i18n: {
    defaultLocale: 'de',
    locales: ['en', 'de'],
  },
  localePath: path.resolve('./public/locales'),
  react: {
    useSuspense: false,
    wait: true,
  },
};

```

## Your Environment

```
"node": v18.7.0
"next": "^12.3.1",
"next-i18next": "^12.1.0",
"os": Mac
```

next and i18next was working fine before i upgraded.

Thank you!

**Comment by adrai** [comment]
Can you please create a minimal reproducible example.
This example seems to work: https://github.com/i18next/next-i18next/tree/master/examples/simple

btw: the react wait option is very old and does not exist anymore, and the useSuspense option is automatically set to false, so should not be necessary anymore.

**Comment by sajadghawami** [comment]
@adrai thank you for the quick reply.

While trying to create a small reproducible example i found out that it didn't have to do with `next-i18next` but it was a problem with `apollo-client` - so i guess thank you :).
