### ISSUE TITLE
Setting interpolation prefix and/or suffix causes namespace resolution error

### ISSUE THREAD

**Issue by jamsinclair** [i18next/next-i18next#2099]
## 🐛 Bug Report

Setting the `interpolation.prefix` and/or `interpolation.suffix` config causes namespace resolution to fail with an error.

Not sure if this is a bug or intentional? Thought I'd make a report in case anyone else encounters it. This issue can be mitigated by setting the config field `localeStructure` and use the new prefixes in the string.
e.g. If prefix and suffix is `{` and `}` you can fix the issue the issue with the following:
```js
module.exports = {
  // ... other config
  interpolation: {
    prefix: '{',
    suffix: '}',
  },
  localeStructure: '{lng}/{ns}',
}
```

## To Reproduce

I tried creating a codesandbox reproduction but ran into issues with their Platform.

Steps:
1. Copy the `examples/simple` template from this Repository
2. Update `next-i18next.config.js` file with the following
```js
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
  },
  interpolation: {
    prefix: '{',
    suffix: '}',
  },
}
```
3. Run `npm run dev`

```
error - Error: Default namespace not found at public/locales/{en}/{common}.json
    at createConfig (/Users/anon-user/node_modules/next-i18next/dist/commonjs/config/createConfig.js:162:19)
    at _callee$ (/Users/anon-user/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:94:53)
    at tryCatch (/Users/anon-user/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/Users/anon-user/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/Users/anon-user/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/Users/anon-user/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/anon-user/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  page: '/'
}
```

## Expected behavior

Setting the interpolation prefix and/or suffix should not throw an error

**Comment by jamsinclair** [comment]
https://github.com/i18next/next-i18next/blob/502dfcf4a2552500e58190681ba9b5cd821120eb/src/config/defaultConfig.ts#L5
I believe one approach to fixing this would be to build this string dynamically with the resolved interpolation prefix and suffix.

**Comment by adrai** [comment]
Happy to review a PR 👍
